[env:ATmega328P]
platform = atmelavr
board = ATmega328P
framework = arduino
monitor_speed = 57600
lib_deps =
  coryjfowler/mcp_can
  LiquidCrystal I2C

; --- SETARI CUSTOM PENTRU UPLOAD DIRECT PRIN USB ---
upload_protocol = custom
upload_flags =
  -C
  ${platformio.packages_dir}/tool-avrdude/avrdude.conf
  -p
  $BOARD_MCU
  -c
  xplainedmini
  -P
  usb
upload_command = avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i